### ISSUE TITLE
make your example stupid-proof

### ISSUE THREAD

**Issue by Hematop** [BinetReseau/polytechnique-beamer#3]
Hey! Just managed to install beamer, and it seems to work, but I had my head scratching for more than a few moments for the stupidest of issues.
The example you put on the wiki doesn't compile straight away. I now know it's because I had to choose which line to comment out, but when pdftex refused to compile it I didn't think at first that it was because of the sample, and hadn't even read it ^^
I'd suggest commenting out its line 6 (or lines 3-4), to spare others the time it took me to realize this.
Thanks!
t

**Comment by w2ak** [comment]
Hello,

As this might be a reading issue, I don't believe that commenting out one of the two blocks will make it more stupid-proof.
Indeed there is no reason for me to favor one or the other compilation method, which I would actually be doing by commenting out one of the two blocks.

Furthermore, even though the text _displayed on the wiki_ shows both examples, the `tex` file that can be downloaded under the text space and that is supposed to compile _does not_ include both possibilities.
